### ISSUE TITLE
can not update slots

### ISSUE THREAD

**Issue by MLS-EA69** [trustcrypto/OnlyKey-App#123] opened 2020-07-30 03:34 UTC
Tried changing static password on any slot by first wiping slot. After doing this and entering new password and pressing "set slot" the key flashes and both "set slot" and "wipe slot" are greyed out and app does not return to main slot screen. This happens with more than one Only Key.
I've reloaded the app. I have latest firmware loaded, latest Mac OS software.

**Comment by MLS-EA69** [comment] 2020-07-30 04:49
I think I figured it out.
The  quotation character when typed as " apparently is rejected by Only Key.
 It must be displayed as ”  angled laterally downward versus straight down which is how apparently how some applications/keyboards? type/save this.
Zoom in on the screen and you can see the difference.

**Comment by onlykey** [comment] 2020-11-11 21:12
I am not able to reproduce this. Setting """ as a value in the app seems to work correctly.

**Comment by rodgolpe** [comment] 2020-11-20 03:19
Closing. Still unable to reproduce.
![image](https://user-images.githubusercontent.com/601129/99753851-1da91700-2ab5-11eb-8031-7451bcdbd98d.png)
![image](https://user-images.githubusercontent.com/601129/99753904-429d8a00-2ab5-11eb-86be-f83e99144760.png)

**Closed by rodgolpe** 2020-11-20 03:19 UTC
